spring.application.name=challenge-softtek-api

spring.data.mongodb.uri=mongodb+srv://fiap:280799@cluster0.nkq2jks.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=challengeSofttekDB

server.port=8080

jwt.secret=NjQ4MjVhM2YwZmFiYThmNGMwZjUzODhhMWI4YTcxYTY2NzlmMTQ4Mzg4MzM2NTcwYmNmNDc1MzJmNzNiOWJkMQ==

jwt.expiration=3600000

logging.level.br.com.fiap.challengeSofttekAPI=INFO

logging.level.org.springframework=WARN

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

logging.file.name=logs/application.log

logging.file.max-size=10MB

logging.file.max-history=7

logging.file.total-size-cap=1GB

